
/*
 * ---
 *
 *  Copyright (c) 2018 Denis Bogomolov (akaish)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file is a part of KittyORM project (KittyORM Demo), more information at
 * https://akaish.github.io/KittyORMPages/license/
 *
 * ---
 */

package net.akaish.kittyormdemo.sqlite.migrations.migv1;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;

import net.akaish.kitty.orm.KittyDatabaseHelper;
import net.akaish.kitty.orm.configuration.conf.KittyDBHelperConfiguration;
import net.akaish.kitty.orm.configuration.conf.KittyDatabaseConfiguration;
import net.akaish.kitty.orm.dumputils.scripts.KittySQLiteDumpScript;
import net.akaish.kitty.orm.exceptions.KittyRuntimeException;
import net.akaish.kitty.orm.query.KittySQLiteQuery;

import java.util.LinkedList;

/**
 * Created by akaish on 24.11.18.
 * @author akaish (Denis Bogomolov)
 */

public class EncryptionHelper extends KittyDatabaseHelper {

    public EncryptionHelper(Context context, KittyDBHelperConfiguration helperCfg,
                            KittyDatabaseConfiguration conf) {
        super(context, helperCfg, conf);
    }

    public EncryptionHelper(Context context, KittyDBHelperConfiguration helperCfg,
                            KittyDatabaseConfiguration conf,
                            SQLiteDatabase.CursorFactory cursorFactory) {
        super(context, helperCfg, conf, cursorFactory);
    }

    public EncryptionHelper(Context context, KittyDBHelperConfiguration helperCfg,
                            KittyDatabaseConfiguration conf,
                            SQLiteDatabase.CursorFactory cursorFactory,
                            LinkedList<KittySQLiteQuery> createSchemaAutogeneratedScript,
                            LinkedList<KittySQLiteQuery> dropSchemaAutogeneratedScript,
                            KittySQLiteDumpScript afterCreateScript,
                            KittySQLiteDumpScript afterMigrateScript) {
        super(context, helperCfg, conf, cursorFactory, createSchemaAutogeneratedScript,
                dropSchemaAutogeneratedScript, afterCreateScript, afterMigrateScript);
    }

    public SQLiteDatabase getWritableDatabase(String pwd) {
        return super.getWritableDatabase(pwd);
    }

    public SQLiteDatabase getReadableDatabase(String pwd) {
        return super.getReadableDatabase(pwd);
    }
}
